In [27]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [28]:
#lendo arquivo
df = pd.read_csv('../data/student_productivity.csv')

In [29]:
df.head()

,student_id,age,gender,academic_level,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,...,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,internet_quality,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
0,1,18,Other,High School,7.64,1.56,2.20,3.05,2.19,6.52,...,81,38,1,0,Good,10,43.05,31.77,73.65,50.16
1,2,18,Other,High School,2.21,2.22,2.10,1.65,2.55,5.97,...,111,339,0,0,Good,3,15.92,37.00,13.70,1.00
2,3,22,Male,High School,3.45,0.00,0.29,1.34,2.08,8.39,...,68,266,0,1,Good,8,27.39,34.37,45.15,18.30
3,4,17,Other,High School,5.75,2.08,3.01,2.27,2.20,6.31,...,113,480,1,1,Poor,3,22.31,77.31,20.92,9.37
4,5,19,Other,High School,6.83,1.72,3.33,2.65,0.70,8.01,...,121,24,1,0,Good,8,38.11,39.53,59.23,27.81

In [30]:
# analisando o shape e as colunas do df
print(df.shape)
print(df.columns)

(5000, 21)
Index(['student_id', 'age', 'gender', 'academic_level', 'study_hours',
       'self_study_hours', 'online_classes_hours', 'social_media_hours',
       'gaming_hours', 'sleep_hours', 'screen_time_hours', 'exercise_minutes',
       'caffeine_intake_mg', 'part_time_job', 'upcoming_deadline',
       'internet_quality', 'mental_health_score', 'focus_index',
       'burnout_level', 'productivity_score', 'exam_score'],
      dtype='object')

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            5000 non-null   int64
 1   age                   5000 non-null   int64
 2   gender                5000 non-null   object
 3   academic_level        5000 non-null   object
 4   study_hours           5000 non-null   float64
 5   self_study_hours      5000 non-null   float64
 6   online_classes_hours  5000 non-null   float64
 7   social_media_hours    5000 non-null   float64
 8   gaming_hours          5000 non-null   float64
 9   sleep_hours           5000 non-null   float64
 10  screen_time_hours     5000 non-null   float64
 11  exercise_minutes      5000 non-null   int64
 12  caffeine_intake_mg    5000 non-null   int64
 13  part_time_job         5000 non-null   int64
 14  upcoming_deadline     5000 non-null   int64
 15  internet_quality      5000 non-null   object
 16  mental_health_score   5000 non-null   int64
 17  focus_index           5000 non-null   float64
 18  burnout_level         5000 non-null   float64
 19  productivity_score    5000 non-null   float64
 20  exam_score            5000 non-null   float64
dtypes: float64(11), int64(7), object(3)
memory usage: 820.4+ KB

In [32]:
#Verificando a presença de valores duplicados e valores nulos
print(f'Número de duplicatas = {df.duplicated().sum()}\n')
print(f'Soma de valores nulos: \n{df.isnull().sum()}')

Número de duplicatas = 0

Soma de valores nulos:
student_id              0
age                     0
gender                  0
academic_level          0
study_hours             0
self_study_hours        0
online_classes_hours    0
social_media_hours      0
gaming_hours            0
sleep_hours             0
screen_time_hours       0
exercise_minutes        0
caffeine_intake_mg      0
part_time_job           0
upcoming_deadline       0
internet_quality        0
mental_health_score     0
focus_index             0
burnout_level           0
productivity_score      0
exam_score              0
dtype: int64

In [33]:
# Unindo colunas 
#Somei as horas de estudo total e removi as respectivas colunas
df['study_hours_total'] = df['study_hours'] + df['self_study_hours'] + df['online_classes_hours']
df = df.drop(['study_hours','self_study_hours','online_classes_hours'],axis=1)
df['study_hours_total']

0       11.40
1        6.53
2        3.74
3       10.84
4       11.88
        ...
4995     5.89
4996     7.00
4997    11.04
4998     7.94
4999    11.91
Name: study_hours_total, Length: 5000, dtype: float64

In [34]:
#criando a coluna de tempo de tela voltado para o lazer
# aqui eu somo tanto as horas gastadas com jogos quanto com as redes sociais
df['leisure_screen_time'] = df['gaming_hours'] + df['social_media_hours']
df = df.drop(['gaming_hours','social_media_hours'],axis=1)
df['leisure_screen_time'].head()

0    5.24
1    4.20
2    3.42
3    4.47
4    3.35
Name: leisure_screen_time, dtype: float64

In [35]:
df['internet_quality'].sample(10)

4575    Average
731        Poor
1173    Average
3781       Poor
184     Average
4035       Poor
3176       Poor
4250       Good
858        Good
4567       Good
Name: internet_quality, dtype: object

In [36]:
# etapa de encoding
internet_categorias = ['Poor','Average','Good']
academic_categorias = ['High School','Undergraduate','Postgraduate']

encoder = OrdinalEncoder(categories=[internet_categorias,academic_categorias])
df[['internet_quality','academic_level']] = encoder.fit_transform(df[['internet_quality','academic_level']])

In [37]:
# verificando os dados
df.head(20)

,student_id,age,gender,academic_level,sleep_hours,screen_time_hours,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,internet_quality,mental_health_score,focus_index,burnout_level,productivity_score,exam_score,study_hours_total,leisure_screen_time
0,1,18,Other,0.0,6.52,6.47,81,38,1,0,2.0,10,43.05,31.77,73.65,50.16,11.40,5.24
1,2,18,Other,0.0,5.97,6.05,111,339,0,0,2.0,3,15.92,37.00,13.70,1.00,6.53,4.20
2,3,22,Male,0.0,8.39,7.62,68,266,0,1,2.0,8,27.39,34.37,45.15,18.30,3.74,3.42
3,4,17,Other,0.0,6.31,11.67,113,480,1,1,0.0,3,22.31,77.31,20.92,9.37,10.84,4.47
4,5,19,Other,0.0,8.01,10.02,121,24,1,0,2.0,8,38.11,39.53,59.23,27.81,11.88,3.35
5,6,25,Male,1.0,8.34,8.06,110,288,0,1,1.0,8,30.52,33.64,36.20,18.53,7.40,6.03
6,7,22,Other,0.0,7.61,11.34,19,123,1,1,0.0,6,33.26,62.01,37.59,10.35,8.24,5.01
7,8,17,Male,0.0,7.62,7.27,135,379,1,0,2.0,1,31.98,45.98,45.04,19.89,14.64,4.89
8,9,16,Female,1.0,8.29,8.24,101,308,1,0,1.0,10,30.23,49.44,61.83,30.73,8.44,5.24
9,10,17,Female,0.0,5.43,7.79,142,415,1,0,1.0,9,20.26,60.78,29.06,8.99,5.43,5.33
10,11,25,Other,2.0,6.40,4.94,146,24,1,1,0.0,8,19.21,48.25,24.48,11.65,7.92,3.87
11,12,16,Male,0.0,7.08,7.68,130,157,0,0,2.0,2,25.04,36.14,31.13,15.01,9.65,3.61
12,13,16,Other,2.0,4.96,8.80,93,193,1,0,2.0,10,32.97,51.79,48.33,22.09,6.53,5.07
13,14,25,Other,1.0,6.17,10.88,58,298,0,0,0.0,7,31.13,50.49,39.30,22.12,8.71,5.47
14,15,19,Other,2.0,7.19,6.94,139,34,0,0,1.0,6,31.07,28.00,50.61,29.83,7.44,2.19
15,16,20,Other,1.0,5.09,7.39,97,413,0,0,1.0,4,21.66,41.97,26.95,14.69,10.30,4.88
16,17,16,Other,1.0,8.00,5.63,78,297,1,1,0.0,4,32.28,58.06,28.09,13.12,9.27,4.02
17,18,16,Male,1.0,6.75,6.21,60,134,1,1,2.0,8,27.96,60.78,37.66,14.18,9.47,4.81
18,19,20,Other,2.0,6.23,8.47,85,56,1,0,0.0,2,13.74,54.29,24.66,6.54,8.47,5.49
19,20,17,Other,2.0,5.48,7.07,133,362,0,0,0.0,5,34.27,48.32,11.13,1.00,4.89,0.93

In [38]:
df.columns

Index(['student_id', 'age', 'gender', 'academic_level', 'sleep_hours',
       'screen_time_hours', 'exercise_minutes', 'caffeine_intake_mg',
       'part_time_job', 'upcoming_deadline', 'internet_quality',
       'mental_health_score', 'focus_index', 'burnout_level',
       'productivity_score', 'exam_score', 'study_hours_total',
       'leisure_screen_time'],
      dtype='object')

In [39]:
# removendo outras colunas que não serão relevantes 
df = df.drop(['student_id','gender'],axis=1)

In [40]:
df.to_csv('../data/student_productivity_cleaned.csv',index=False)